apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mern-chart.fullname" . }}-frontend
spec:
  replicas: {{ alexa055.2 }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: {{ alexa055.frontend:latest }}
          ports:
            - containerPort: {{ alexa055.80 }}
