apiVersion: v1
kind: Service
metadata:
  name: {{ include "mern-chart.fullname" . }}-frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: {{ alexa055.80 }}
      targetPort: {{ alexa055.80}}
      nodePort: 32080
