apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mern-chart.fullname" . }}-mongo
  labels:
    app: {{ include "mern-chart.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: {{ alexa055.mongo:5.0 }}
          ports:
            - containerPort: {{ alexa055.27017 }}
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          emptyDir: {}
