pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('alexa055')
        DOCKERHUB_USERNAME = 'alexa055'
    }

    stages {
        stage('Build Backend') {
            steps {
                dir('backend') {
                    script {
                        docker.build("${alexa055}/backend:${env.BUILD_NUMBER}")
                    }
                }
            }
        }

        stage('Build Frontend') {
            steps {
                dir('frontend') {
                    script {
                        docker.build("${alexa055}/frontend:${env.BUILD_NUMBER}")
                    }
                }
            }
        }

        stage('Push Images') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'alexa055') {
                        docker.image("${alexa055}/backend:${env.BUILD_NUMBER}").push()
                        docker.image("${alexa055}/frontend:${env.BUILD_NUMBER}").push()
                        sh "docker image tag ${alexa055}/backend:${env.BUILD_NUMBER} ${alexa055}/backend:latest"
                        sh "docker image tag ${alexa055}/frontend:${env.BUILD_NUMBER} ${alexa055}/frontend:latest"
                        docker.image("${alexa055}/backend:latest").push()
                        docker.image("${alexa055}/frontend:latest").push()
                    }
                }
            }
        }

        stage('Deploy via Helm') {
            steps {
                withCredentials([string(credentialsId: 'KUBECONFIG_BASE64', variable: 'KUBECONFIG_B64')]) {
                    sh 'echo $KUBECONFIG_B64 | base64 --decode > kubeconfig && export KUBECONFIG=$PWD/kubeconfig'
                }
                dir('helm-chart/mern-chart') {
                    sh 'helm upgrade --install mern-app . --namespace mern --create-namespace --wait'
                }
            }
        }
    }
}
